[book]
authors = ["Matthew Griffiths"]
title = "docs.mutiny.systems"
language = "en"
multilingual = false
src = "src"
[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-admonish.css"]
default-theme = "macchiato"
preferred-dark-theme = "macchiato"